spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=example-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://example-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/example/**