INSERT INTO COUNTRY (CODE, NAME) VALUES ('IN', 'India');
INSERT INTO COUNTRY (CODE, NAME) VALUES ('US', 'United States');
INSERT INTO COUNTRY (CODE, NAME) VALUES ('JP', 'Japan');
INSERT INTO COUNTRY (CODE, NAME) VALUES ('AU', 'Australia');